name: Keep Render App Awake

on:
  schedule:
    - cron: '*/5 * * * *'   # يشغّل المهمة كل 5 دقائق
  workflow_dispatch:        # يسمح بتشغيلها يدويًا من GitHub Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          echo "Pinging Render app to keep it awake..."
          curl -fsS -o /dev/null https://aliwalhaq-records-86ps.onrender.com/ || true
